name: Deploy a preview to Firebase on PR

on:
  pull_request:
    branches: [main]

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}-${{ matrix.node-version }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm run test:ci

      - name: Run E2E test
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:4200'
          config: baseUrl=http://localhost:4200

      - name: Build it 👷🏻‍♂️
        run: |
          npm run build

      - name: Deploy Preview 🚀
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_POC_IONIC_LOGIN }}'
          projectId: poc-ionic-login
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
